# Specify Python and versions to test
language: python
python:
  - 3.6
  - 3.7
  - 3.8

# Preliminary scripts
before_install:
  - pip install llvmlite

# Installation scripts
install:
  - pip install -e .
  - pip install -r lib/tests/requirements.txt

# Test script
script: pytest lib/tests